owner: erozanov
repo: status

sites:
  - name: "Synology DSM"
    url: https://status.anonym.keenetic.pro
    check: "http"

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My Home Infrastructure
  introTitle: "Мониторинг домашнего сервера Synology через Keenetic Peak"
  introMessage: "Статус-страница обновляется автоматически каждые 5 минут с помощью GitHub Actions."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: telegram
    payload:
      token: $TELEGRAM_BOT_TOKEN
      chatId: $TELEGRAM_CHAT_ID

assignees:
  - erozanov
