owner: erozanov
repo: status
sites:
  - name: "Synology DSM"
    url: https://status.anonym.keenetic.pro
    check: "http"
status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My Home Infrastructure
  introTitle: "Monitoring"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
notifications:
  - type: telegram
assignees:
  - erozanov
