# 1. Укажите ваши данные GitHub
owner: erozanov
repo: status

# 2. Мониторинг вашего Synology
sites:
  - name: "Synology DSM"
    url: https://status.anonym.keenetic.pro
    check: "http"

# 3. Настройка страницы статуса
status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My Home Infrastructure
  introTitle: "Мониторинг домашнего сервера Synology через Keenetic Peak"
  introMessage: "Статус-страница обновляется автоматически каждые 5 минут с помощью GitHub Actions."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# 4. Уведомления в Telegram (используют секреты, которые вы уже добавили)
notifications:
  - type: telegram
    payload:
      token: $TELEGRAM_BOT_TOKEN
      chatId: $TELEGRAM_CHAT_ID

# Дополнительные настройки для работы GitHub Actions
assignees:
  - erozanov
